using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace WorldStreamer2;

public class Streamer : MonoBehaviour
{
	[Tooltip("This checkbox deactivates streamer and unload or doesn't load it's data.")]
	public bool streamerActive = true;

	public static string STREAMERTAG = "SceneStreamer";

	[Tooltip("Drag and drop here your scene collection prefab. You could find it in catalogue with scenes which were generated by scene splitter.")]
	public List<SceneCollectionManager> sceneCollectionManagers;

	[Header("Settings")]
	[Tooltip("Frequancy in seconds in which you want to check if grid element is close /far enough to load/unload.")]
	public float positionCheckTime = 0.1f;

	[Tooltip("Time in seconds after which grid element will be unloaded.")]
	public float destroyTileDelay = 2f;

	[Tooltip("Number of empty frames between loading actions.")]
	public int sceneLoadWaitFrames = 2;

	[Space(10f)]
	[Tooltip("If you want to fix small holes from LODs system at unity terrain borders, drag and drop object here from scene hierarchy that contains our \"Terrain Neighbours\" script.")]
	public TerrainNeighbours terrainNeighbours;

	[Space(10f)]
	[Tooltip("Enable looping system, each layer is streamed independently, so if you want to synchronize them, they should have the same XYZ size. More info at manual.")]
	public bool looping;

	public bool overideRangeLimit = true;

	public bool overideScenesLimits = true;

	[Space(10f)]
	[Header("Player Settings")]
	[Tooltip("Drag and drop here, an object that system have to follow during streaming process.")]
	[SerializeField]
	private Transform _player;

	[Tooltip("Streamer will wait for player spawn and fill it automatically")]
	public bool spawnedPlayer;

	[HideInInspector]
	public string playerTag = "Player";

	[HideInInspector]
	public bool showLoadingScreen = true;

	[HideInInspector]
	public UILoadingStreamer loadingStreamer;

	[HideInInspector]
	public bool initialized;

	[HideInInspector]
	public int tilesToLoad = int.MaxValue;

	[HideInInspector]
	public int tilesLoaded;

	[HideInInspector]
	public WorldMover worldMover;

	[HideInInspector]
	public Vector3 currentMove = Vector3.zero;

	private List<SceneSplit> scenesToLoad = new List<SceneSplit>();

	private int sceneLoadFrameNext;

	private bool sceneLoadFramesNextWaited;

	public StreamerLoadingManager loadingManager;

	private static bool canUnload = true;

	private static float waitTillNextUnload = 20f;

	private static bool unloadNext = false;

	public Transform player
	{
		get
		{
			if (spawnedPlayer && _player == null && !string.IsNullOrEmpty(playerTag))
			{
				GameObject gameObject = GameObject.FindGameObjectWithTag(playerTag);
				if (gameObject != null)
				{
					_player = gameObject.transform;
				}
			}
			return _player;
		}
		set
		{
			_player = value;
		}
	}

	public float LoadingProgress
	{
		get
		{
			if (tilesToLoad <= 0)
			{
				return 1f;
			}
			return (float)tilesLoaded / (float)tilesToLoad;
		}
	}

	private void Awake()
	{
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			sceneCollectionManager.ResetPosition();
		}
	}

	private void Start()
	{
		loadingManager = new StreamerLoadingManager
		{
			streamer = this
		};
		if (sceneCollectionManagers != null && sceneCollectionManagers.Count > 0)
		{
			PrepareScenesArray();
			StartCoroutine(PositionChecker());
			canUnload = true;
		}
		else
		{
			base.enabled = false;
			Debug.LogError("No scene collection in streamer");
		}
	}

	private void PrepareScenesArray()
	{
		Vector2Int xLimits = Vector2Int.zero;
		Vector2Int yLimits = Vector2Int.zero;
		Vector2Int zLimits = Vector2Int.zero;
		if (sceneCollectionManagers.Count > 1)
		{
			sceneCollectionManagers[0].GetSceneCollectionWolrdLimits(out xLimits, out yLimits, out zLimits);
			string[] array = new string[5];
			Vector2Int vector2Int = xLimits;
			array[0] = vector2Int.ToString();
			array[1] = " ";
			vector2Int = yLimits;
			array[2] = vector2Int.ToString();
			array[3] = " ";
			vector2Int = zLimits;
			array[4] = vector2Int.ToString();
			Debug.Log(string.Concat(array));
		}
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			sceneCollectionManager.unloadRangeConnectParent = null;
		}
		foreach (SceneCollectionManager sceneCollectionManager2 in sceneCollectionManagers)
		{
			if (sceneCollectionManager2.useUnloadRangeConnect && sceneCollectionManager2.unloadRangeConnect != null)
			{
				sceneCollectionManager2.unloadRangeConnect.unloadRangeConnectParent = sceneCollectionManager2;
			}
			if (overideScenesLimits)
			{
				sceneCollectionManager2.CalculateLoadingLimits(looping, overideRangeLimit, overideScenesLimits, xLimits, yLimits, zLimits);
				sceneCollectionManager2.PrepareScenesArray(overideRangeLimit, overideScenesLimits, xLimits, yLimits, zLimits);
			}
			else
			{
				sceneCollectionManager2.CalculateLoadingLimits(looping, overideRangeLimit);
				sceneCollectionManager2.PrepareScenesArray(overideRangeLimit);
			}
		}
	}

	public static void SceneNameToPos(SceneCollectionManager sceneCollectionManager, string sceneName, out int posX, out int posY, out int posZ)
	{
		posX = 0;
		posY = 0;
		posZ = 0;
		string[] array = sceneName.Replace(sceneCollectionManager.prefixScene, "").Replace(".unity", "").Split(new char[1] { '_' }, StringSplitOptions.RemoveEmptyEntries);
		foreach (string text in array)
		{
			if (text[0] == 'x')
			{
				posX = int.Parse(text.Replace("x", ""));
			}
			if (text[0] == 'y')
			{
				posY = int.Parse(text.Replace("y", ""));
			}
			if (text[0] == 'z')
			{
				posZ = int.Parse(text.Replace("z", ""));
			}
		}
	}

	public static int mod(int x, int m)
	{
		return (x % m + m) % m;
	}

	public void OnSceneLoaded(Scene scene, SceneSplit split)
	{
		GameObject[] rootGameObjects = scene.GetRootGameObjects();
		if (rootGameObjects.Length != 0)
		{
			AddSceneGOMin(split, rootGameObjects[0]);
		}
	}

	public void AddSceneGOMin(SceneSplit split, GameObject sceneGO)
	{
		SceneCollectionManager sceneCollectionManager = split.sceneCollectionManager;
		int posX = 0;
		int posY = 0;
		int posZ = 0;
		SceneNameToPos(split.sceneCollectionManager, split.sceneName, out posX, out posY, out posZ);
		Vector3Int vector3Int = new Vector3Int(posX, posY, posZ);
		sceneGO.GetComponent<SceneSplitManager>();
		tilesLoaded++;
		float num = split.posX - vector3Int.x;
		float num2 = split.posY - vector3Int.y;
		float num3 = split.posZ - vector3Int.z;
		Vector3 vector = new Vector3((float)sceneCollectionManager.xSize * num, (float)sceneCollectionManager.ySize * num2, (float)sceneCollectionManager.zSize * num3) + currentMove + new Vector3(split.posXLimitMove, split.posYLimitMove, split.posZLimitMove);
		split.sceneGo = sceneGO;
		split.scene = sceneGO.scene;
		split.loadingFinished = true;
		split.sceneCollectionManager.currentlySceneLoading--;
		sceneGO.transform.position = vector;
		SceneCollectionManager sceneCollectionManager2 = null;
		if (sceneCollectionManager.useUnloadRangeConnect && sceneCollectionManager.unloadRangeConnect != null)
		{
			sceneCollectionManager2 = sceneCollectionManager.unloadRangeConnect;
		}
		if (sceneCollectionManager.unloadRangeConnectParent != null && sceneCollectionManager.unloadRangeConnectParent.useUnloadRangeConnect)
		{
			sceneCollectionManager2 = sceneCollectionManager.unloadRangeConnectParent;
		}
		if (!(sceneCollectionManager2 != null))
		{
			return;
		}
		float num4 = sceneCollectionManager2.loadedScenes.Count;
		for (int i = 0; (float)i < num4; i++)
		{
			SceneSplit sceneSplit = sceneCollectionManager2.loadedScenes[i];
			if (sceneSplit.loadingFinished && split.basePosX == sceneSplit.basePosX && split.basePosY == sceneSplit.basePosY && split.basePosZ == sceneSplit.basePosZ && vector == sceneSplit.sceneGo.transform.position)
			{
				UnloadScenesSync(sceneSplit);
				break;
			}
		}
	}

	private void Update()
	{
		LoadLevelAsyncManage();
		loadingManager.Update();
	}

	private void LoadLevelAsyncManage()
	{
		if (scenesToLoad.Count <= 0)
		{
			return;
		}
		if (LoadingProgress < 1f || (sceneLoadFramesNextWaited && sceneLoadFrameNext <= 0))
		{
			sceneLoadFramesNextWaited = false;
			sceneLoadFrameNext = sceneLoadWaitFrames;
			scenesToLoad = scenesToLoad.OrderBy((SceneSplit x) => x.sceneCollectionManager.priority).ToList();
			int num = 0;
			while (scenesToLoad.Count > 0 && num < scenesToLoad.Count)
			{
				SceneSplit sceneSplit = scenesToLoad[num];
				if (sceneSplit.sceneCollectionManager.currentlySceneLoading < sceneSplit.sceneCollectionManager.maxParallelSceneLoading)
				{
					scenesToLoad.Remove(sceneSplit);
					sceneSplit.sceneCollectionManager.currentlySceneLoading++;
					loadingManager.LoadSceneAsync(sceneSplit);
					num--;
				}
				num++;
			}
		}
		else
		{
			sceneLoadFramesNextWaited = true;
			sceneLoadFrameNext--;
		}
	}

	private IEnumerator PositionChecker()
	{
		while (true)
		{
			if (spawnedPlayer && player == null && !string.IsNullOrEmpty(playerTag))
			{
				GameObject gameObject = GameObject.FindGameObjectWithTag(playerTag);
				if (gameObject != null)
				{
					player = gameObject.transform;
				}
			}
			if (streamerActive && player != null)
			{
				CheckPositionTiles();
			}
			else
			{
				bool flag = false;
				foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
				{
					if (sceneCollectionManager.loadedScenes.Count > 0)
					{
						flag = true;
						sceneCollectionManager.ResetPosition();
					}
				}
				if (flag)
				{
					UnloadAllScenes();
				}
			}
			yield return new WaitForSeconds(positionCheckTime);
		}
	}

	public void CheckPositionTiles()
	{
		Vector3 position = player.position;
		position -= currentMove;
		bool flag = false;
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			if (sceneCollectionManager.CheckPosition(position))
			{
				flag = true;
			}
		}
		if (flag)
		{
			SceneLoading();
			Invoke("SceneUnloading", destroyTileDelay);
			if (worldMover != null)
			{
				worldMover.CheckMoverDistance(sceneCollectionManagers[0].xPos, sceneCollectionManagers[0].yPos, sceneCollectionManagers[0].zPos);
			}
		}
	}

	private void SceneLoading()
	{
		if (showLoadingScreen && loadingStreamer != null)
		{
			showLoadingScreen = false;
			if (tilesLoaded >= tilesToLoad)
			{
				tilesToLoad = int.MaxValue;
				tilesLoaded = 0;
			}
		}
		int num = 0;
		int num2 = 0;
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			if (!sceneCollectionManager.active)
			{
				continue;
			}
			int xPos = sceneCollectionManager.xPos;
			int yPos = sceneCollectionManager.yPos;
			int zPos = sceneCollectionManager.zPos;
			int num3 = sceneCollectionManager.loadingRange.x * 2 + 1;
			int num4 = sceneCollectionManager.loadingRange.z * 2 + 1;
			int num5 = 0;
			int num6 = 0;
			int num7 = 0;
			int num8 = -1;
			int num9 = Math.Max(num3, num4);
			int num10 = num9 * num9;
			for (int i = 0; i < num10; i++)
			{
				if (-num3 / 2 <= num5 && num5 <= num3 / 2 && -num4 / 2 <= num6 && num6 <= num4 / 2)
				{
					for (int j = 0; j <= sceneCollectionManager.loadingRange.y; j++)
					{
						for (int k = -1; k <= 1; k += 2)
						{
							if (j == 0 && k != -1)
							{
								continue;
							}
							num2++;
							if (sceneCollectionManager.useLoadingRangeMin && num5 >= -sceneCollectionManager.loadingRangeMin.x && num5 <= sceneCollectionManager.loadingRangeMin.x && j >= -sceneCollectionManager.loadingRangeMin.y && j <= sceneCollectionManager.loadingRangeMin.y && num6 >= -sceneCollectionManager.loadingRangeMin.z && num6 <= sceneCollectionManager.loadingRangeMin.z)
							{
								continue;
							}
							xPos = num5 + sceneCollectionManager.xPos;
							yPos = j * k + sceneCollectionManager.yPos;
							zPos = num6 + sceneCollectionManager.zPos;
							Vector3Int key = new Vector3Int(xPos, yPos, zPos);
							float posXLimitMove = 0f;
							int num11 = 0;
							float posYLimitMove = 0f;
							int num12 = 0;
							float posZLimitMove = 0f;
							int num13 = 0;
							if (looping)
							{
								if (sceneCollectionManager.xSplitIs)
								{
									int value = mod(xPos + Mathf.Abs(sceneCollectionManager.xLoadingLimitx), sceneCollectionManager.xLoadingRange) + sceneCollectionManager.xLoadingLimitx;
									num11 = (int)Math.Ceiling((float)(xPos - sceneCollectionManager.xLoadingLimity) / (float)sceneCollectionManager.xLoadingRange) * sceneCollectionManager.xLoadingRange;
									posXLimitMove = num11 * sceneCollectionManager.xSize;
									key[0] = value;
								}
								if (sceneCollectionManager.ySplitIs)
								{
									int value2 = mod(yPos + Mathf.Abs(sceneCollectionManager.yLoadingLimitx), sceneCollectionManager.yLoadingRange) + sceneCollectionManager.yLoadingLimitx;
									num12 = (int)Math.Ceiling((float)(yPos - sceneCollectionManager.yLoadingLimity) / (float)sceneCollectionManager.yLoadingRange) * sceneCollectionManager.yLoadingRange;
									posYLimitMove = num12 * sceneCollectionManager.ySize;
									key[1] = value2;
								}
								if (sceneCollectionManager.zSplitIs)
								{
									int value3 = mod(zPos + Mathf.Abs(sceneCollectionManager.zLoadingLimitx), sceneCollectionManager.zLoadingRange) + sceneCollectionManager.zLoadingLimitx;
									num13 = (int)Math.Ceiling((float)(zPos - sceneCollectionManager.zLoadingLimity) / (float)sceneCollectionManager.zLoadingRange) * sceneCollectionManager.zLoadingRange;
									posZLimitMove = num13 * sceneCollectionManager.zSize;
									key[2] = value3;
								}
							}
							if (sceneCollectionManager.scenesArray.TryGetValue(key, out var value4) && !value4.loaded)
							{
								value4.loaded = true;
								value4.posXLimitMove = posXLimitMove;
								value4.xDeloadLimit = num11;
								value4.posYLimitMove = posYLimitMove;
								value4.yDeloadLimit = num12;
								value4.posZLimitMove = posZLimitMove;
								value4.zDeloadLimit = num13;
								scenesToLoad.Add(value4);
								sceneCollectionManager.loadedScenes.Add(value4);
								num++;
							}
						}
					}
				}
				if (num5 == num6 || (num5 < 0 && num5 == -num6) || (num5 > 0 && num5 == 1 - num6))
				{
					int num14 = num7;
					num7 = -num8;
					num8 = num14;
				}
				num5 += num7;
				num6 += num8;
			}
		}
		tilesToLoad = num;
		initialized = true;
	}

	private void SceneUnloading()
	{
		List<SceneSplit> list = new List<SceneSplit>();
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			float num = sceneCollectionManager.loadedScenes.Count;
			for (int i = 0; (float)i < num; i++)
			{
				SceneSplit sceneSplit = sceneCollectionManager.loadedScenes[i];
				if (sceneCollectionManager.active)
				{
					if (sceneCollectionManager.unloadRangeConnectParent == null)
					{
						if ((Mathf.Abs(sceneSplit.posX + sceneSplit.xDeloadLimit - sceneCollectionManager.xPos) > sceneCollectionManager.deloadingRange.x || Mathf.Abs(sceneSplit.posY + sceneSplit.yDeloadLimit - sceneCollectionManager.yPos) > sceneCollectionManager.deloadingRange.y || Mathf.Abs(sceneSplit.posZ + sceneSplit.zDeloadLimit - sceneCollectionManager.zPos) > sceneCollectionManager.deloadingRange.z) && sceneSplit.sceneGo != null)
						{
							list.Add(sceneSplit);
						}
						if (sceneCollectionManager.useLoadingRangeMin && !sceneCollectionManager.useUnloadRangeConnect && Mathf.Abs(sceneSplit.posX + sceneSplit.xDeloadLimit - sceneCollectionManager.xPos) <= sceneCollectionManager.loadingRangeMin.x && Mathf.Abs(sceneSplit.posY + sceneSplit.yDeloadLimit - sceneCollectionManager.yPos) <= sceneCollectionManager.loadingRangeMin.y && Mathf.Abs(sceneSplit.posZ + sceneSplit.zDeloadLimit - sceneCollectionManager.zPos) <= sceneCollectionManager.loadingRangeMin.z && sceneSplit.sceneGo != null)
						{
							list.Add(sceneSplit);
						}
					}
				}
				else
				{
					list.Add(sceneSplit);
				}
			}
		}
		UnloadScenes(list);
		list.Clear();
		UnloadAssets(this);
	}

	private void UnloadScenesSync(SceneSplit item)
	{
		if (item.sceneGo != null)
		{
			Terrain componentInChildren = item.sceneGo.GetComponentInChildren<Terrain>();
			if ((bool)componentInChildren)
			{
				GameObject obj = componentInChildren.gameObject;
				UnityEngine.Object.Destroy(componentInChildren);
				componentInChildren = null;
				UnityEngine.Object.Destroy(obj);
				obj = null;
			}
		}
		item.loaded = false;
		item.loadingFinished = false;
		item.sceneCollectionManager.loadedScenes.Remove(item);
		item.sceneGo = null;
		loadingManager.UnloadSceneAsync(item.scene);
	}

	private void UnloadScenes(List<SceneSplit> scenesToDestroy)
	{
		foreach (SceneSplit item in scenesToDestroy)
		{
			item.loaded = false;
			item.loadingFinished = false;
			item.sceneCollectionManager.loadedScenes.Remove(item);
			item.sceneGo = null;
			loadingManager.UnloadSceneAsync(item.scene);
		}
		if ((bool)terrainNeighbours)
		{
			terrainNeighbours.CreateNeighbours();
		}
	}

	public void UnloadAllScenes()
	{
		Debug.Log("UnloadAllScenes start");
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			foreach (KeyValuePair<Vector3Int, SceneSplit> item in sceneCollectionManager.scenesArray)
			{
				if (item.Value.sceneGo != null)
				{
					try
					{
						loadingManager.UnloadSceneAsync(item.Value.scene);
					}
					catch (Exception ex)
					{
						Debug.Log(item.Value.sceneName);
						Debug.Log(item.Value.sceneGo.name);
						Debug.Log(item.Value.sceneGo.scene.name);
						Debug.LogError(ex.Message);
					}
				}
				item.Value.loaded = false;
				item.Value.loadingFinished = false;
				item.Value.sceneGo = null;
			}
			sceneCollectionManager.loadedScenes.Clear();
		}
		if ((bool)terrainNeighbours)
		{
			terrainNeighbours.CreateNeighbours();
		}
		UnloadAssets(this);
		Debug.Log("UnloadAllScenes finish");
	}

	public static void UnloadAssets(Streamer streamer)
	{
		if (canUnload)
		{
			canUnload = false;
			streamer.StartCoroutine(streamer.UnloadAssetsWait());
		}
		else
		{
			unloadNext = true;
		}
	}

	public IEnumerator UnloadAssetsWait()
	{
		do
		{
			unloadNext = false;
			Resources.UnloadUnusedAssets();
			yield return new WaitForSeconds(waitTillNextUnload);
		}
		while (unloadNext);
		canUnload = true;
	}

	private void OnDrawGizmosSelected()
	{
		if (sceneCollectionManagers == null)
		{
			return;
		}
		Vector3 zero = Vector3.zero;
		Vector3 zero2 = Vector3.zero;
		Vector3Int zero3 = Vector3Int.zero;
		foreach (SceneCollectionManager sceneCollectionManager in sceneCollectionManagers)
		{
			if (!sceneCollectionManager || !sceneCollectionManager.showDebug || !sceneCollectionManager.active)
			{
				continue;
			}
			Gizmos.color = sceneCollectionManager.color;
			zero.x = ((sceneCollectionManager.xSize == 0) ? 2 : sceneCollectionManager.xSize);
			zero.y = ((sceneCollectionManager.ySize == 0) ? 2 : sceneCollectionManager.ySize);
			zero.z = ((sceneCollectionManager.zSize == 0) ? 2 : sceneCollectionManager.zSize);
			zero3.x = (sceneCollectionManager.xSplitIs ? sceneCollectionManager.loadingRange.x : 0);
			zero3.y = (sceneCollectionManager.ySplitIs ? sceneCollectionManager.loadingRange.y : 0);
			zero3.z = (sceneCollectionManager.zSplitIs ? sceneCollectionManager.loadingRange.z : 0);
			for (int i = -zero3.x + sceneCollectionManager.xPos; i <= zero3.x + sceneCollectionManager.xPos; i++)
			{
				for (int j = -zero3.y + sceneCollectionManager.yPos; j <= zero3.y + sceneCollectionManager.yPos; j++)
				{
					for (int k = -zero3.z + sceneCollectionManager.zPos; k <= zero3.z + sceneCollectionManager.zPos; k++)
					{
						if (!sceneCollectionManager.useLoadingRangeMin || i - sceneCollectionManager.xPos < -sceneCollectionManager.loadingRangeMin.x || i - sceneCollectionManager.xPos > sceneCollectionManager.loadingRangeMin.x || j - sceneCollectionManager.yPos < -sceneCollectionManager.loadingRangeMin.y || j - sceneCollectionManager.yPos > sceneCollectionManager.loadingRangeMin.y || k - sceneCollectionManager.zPos < -sceneCollectionManager.loadingRangeMin.z || k - sceneCollectionManager.zPos > sceneCollectionManager.loadingRangeMin.z)
						{
							if (Application.isPlaying)
							{
								zero2.x = (float)i * zero.x;
								zero2.y = (float)j * zero.y;
								zero2.z = (float)k * zero.z;
							}
							else
							{
								zero2.x = (float)(i - sceneCollectionManager.xPos) * zero.x;
								zero2.y = (float)(j - sceneCollectionManager.yPos) * zero.y;
								zero2.z = (float)(k - sceneCollectionManager.zPos) * zero.z;
							}
							Gizmos.DrawWireCube(zero2 + zero * 0.5f + currentMove, zero);
						}
					}
				}
			}
			Gizmos.color = Color.green;
			if (Application.isPlaying)
			{
				Gizmos.DrawWireCube(new Vector3((float)sceneCollectionManager.xPos * zero.x, (float)sceneCollectionManager.yPos * zero.y, (float)sceneCollectionManager.zPos * zero.z) + zero * 0.5f + currentMove, zero);
			}
			else
			{
				Gizmos.DrawWireCube(zero * 0.5f, zero);
			}
		}
	}
}
